[project]
name = "authorization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pipreqs>=0.5.0",
    "tinydb>=4.8.2",
]
